name: new_version_plus
description: Check if your user has the most recent version of your Flutter app.
version: 0.1.2
homepage: https://github.com/CodesFirst/new_version_plus

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^10.2.1
  http: ^1.6.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0